# Auto-generated by Firmgen — DO NOT EDIT.
# Explicit list of firmware sources + include dirs, refreshed before every
# build. Replaces the old file(GLOB ...) (which cached stale results and could
# escape the project). FW_ROOT is set by the including main/CMakeLists.txt.

set(APP_SOURCES
    "${FW_ROOT}/app/app.c"
    "${FW_ROOT}/app/roof_monitor.c"
    "${FW_ROOT}/app/roof_monitor_baseline.c"
    "${FW_ROOT}/drivers/hcsr04.c"
    "${FW_ROOT}/drivers/rgb_led.c"
    "${FW_ROOT}/services/roof_status_service.c"
    "${FW_ROOT}/utils/helpers/helpers.c"
    "${FW_ROOT}/utils/logger/logger.c"
)

set(FW_INCLUDE_DIRS
    "${FW_ROOT}"
    "${FW_ROOT}/app"
    "${FW_ROOT}/configs"
    "${FW_ROOT}/drivers"
    "${FW_ROOT}/services"
    "${FW_ROOT}/utils/helpers"
    "${FW_ROOT}/utils/logger"
)
